name: CI

on:
    push:
        branches: [master, devops]
    pull_request:
        branches: [master, devops]

jobs:
    Security:
        name: Security Check
        uses: ./.github/workflows/codeql.yaml
        secrets: inherit
        permissions:
            # required for all workflows
            security-events: write

            # required to fetch internal or private CodeQL packs
            packages: read